### ISSUE TITLE
EPIC: MVP

### ISSUE THREAD

**Issue by morganpothoff** [morganpothoff/PATH#1]
## Description
As a STUDENT, I want to keep track of all of my assignments, quizzes, exams, and class events in one location so that I can complete them in a timely manner.

## Context
TAMUHack project for USAA challenge: best remote learning hack

## Possible Implementations
We want a web server that will take input for a student's assignments, quizzes, exams, and more, that will be stored in a database. This information will be displayed as a timeline. The timeline shows the assignment relative to how far away its due date is and how much time each needs for completion.

## Acceptance Criteria
- [ ] Draws timeline
- [ ] Uses data saved in database
- [ ] Allows multiple timelines to be created/stored
- [ ] Notifies student if one event overlaps with another
- [ ] Allows timeline to be shared with others

## Notes
